### ISSUE TITLE
Design The Tour: Create Condition to check new user login for introjs tour

### ISSUE THREAD

**Issue by BaloneyBoy97** [oss-slu/lrda_website#142]
**Original Issue** #138

**Description**

**As** a new user,
**I need** an introductory guided tour to familiarize myself with the core features of the app,
**So that** I can easily navigate the application and have a smoother onboarding experience.

**Tasks**
Install Intro.js:
- [x] Add Intro.js to the project dependencies using command: _pnpm add intro.js_
- [x] Merge Amy's branch to access updated code
- [x] Create condition in code
   - Popup only shows for first time login user.
- [x] Create a test case for your code
- [x] feature meets requirements

**Acceptance Criteria**
- [x] Create at least one test case for you code 
   - [x] Unit test/Integration test/E2E test
- [x] Code is well commented 
- [x] Only commit changes that you physically typed.
- [x] Code should pass the test case before merge

Quick Guide:
https://www.youtube.com/watch?v=wA_YIhumn0M

Code example and test example can be found in branch "Wheres-Religion-Desktop-fall-2024"

This issue will help members new to the project to understand the work flow of the application and familiarize with the project.
