### ISSUE TITLE
Design The Tour: Create guide for map/page

### ISSUE THREAD

**Issue by BaloneyBoy97** [oss-slu/lrda_website#143]
**Original Issue** https://github.com/oss-slu/lrda_website/issues/138

**Description**

**As** a new user,
**I need** an Intro.js tour for the map page to understand its main features,
**So that** I can easily navigate and use the map functionalities and refer back to the tour through the help section if needed.

**Tasks**
Install Intro.js:
- [x] Add Intro.js to the project dependencies using command: _pnpm add intro.js_
- [x] add code to start the IntroJs Tour
    - [x] reference correct button id 
    - [x] regression free
- [x] Create a test case for your code
- [x] feature meets requirements

**Acceptance Criteria**
- [x] Create at least one test case for you code
    - [x] Unit test/Integration test/E2E test
- [x] Code is well commented
- [x] Only commit changes that you physically typed.
- [x] Code should pass the test case before merge

**Quick Guide:**
https://www.youtube.com/watch?v=wA_YIhumn0M

Code example and test example can be found in branch "Wheres-Religion-Desktop-fall-2024"

This issue will help members new to the project to understand the work flow of the application and familiarize with the project.
