### ISSUE TITLE
Create IntroJs Tour Example for Capstone Student Onboarding

### ISSUE THREAD

**Issue by BaloneyBoy97** [oss-slu/lrda_website#146]
**Original Issue** #138

**Description**
**Given** a capstone student accesses the desktop application for the first time,
**When** they log in or begin using the application,
**Then** an Intro.js tour should guide them through the core features, providing a smooth onboarding experience. The tour should serve as an example of the workflow with detailed comments and sufficient support to help the student better understand the project.

**Tasks**
Install Intro.js:
- [x] Add Intro.js to the project dependencies using command: _pnpm add intro.js_
- [x] Add example code to designated file (map/page)
- [x] Comment on code
   - Explain thought process and tech used.
- [x] Create a test case for your code
   - [x] Unit Test
   - [x] Comment each test case to explain testing criteria 
- [x] feature meets requirements

**Acceptance Criteria**
- [x] Create at least one test case for you code 
   - [x] Unit test/Integration test/E2E test
- [x] Code is well commented 
- [x] Only commit changes that you physically typed.
- [x] Code should pass the test case before merge

This issue will help members new to the project to understand the work flow of the application and familiarize with the project.
