### ISSUE TITLE
Continuing Intro.js for User Onboarding in the Create Note Page

### ISSUE THREAD

**Issue by BaloneyBoy97** [oss-slu/lrda_website#149]
**Original Issue** https://github.com/oss-slu/lrda_website/issues/138

**Description**

**As** a new user,
**I need** an Intro.js tour for the create note page to understand its main features,
**So that** I can easily navigate and use the notes functionalities and refer back to the tour through the help section if needed.

**Tasks**
- [x] add code in notes elements module to start the IntroJs Tour
    - [x] Reference the correct button IDs to ensure the tour is triggered properly.
- [x] Ensure the implementation is regression-free.
- [x] Add a "Skip Tour" button that allows users to exit the tour if they do not wish to continue across multiple pages.
- [x] Create a test cases for your code
    - [x] Ensure that the tour starts correctly.
    - [x] Ensure that users can skip or continue the tour seamlessly.
    - [x] Ensure that the tour progresses step-by-step without issues.
- [x] regression free
    - committed code will not break other functionalities or previous commits

**Acceptance Criteria**
- [x] Create at least one test case for you code
    - [x] Unit test to check functionality.
    - [x] Integration test to verify correct operation across components.
- [x] Code is well commented
- [x] Commit only the changes that you’ve made
- [x] Code should pass the test case before merge
- [x] introJs Triggers tour from create note page
- [x] the tour is Continuing from Map/page
- [x] the ability to skip tour
- [x] the tour need to remember its steps so the user can go back and forth between pages and the tour will resume from its previous step
- [x] Logout button need to be referenced at the end of the tour not in map/page

Code example and test example can be found in branch "Wheres-Religion-Desktop-fall-2024"

This issue will help members new to the project to understand the work flow of the application and familiarize with the project.
