### ISSUE TITLE
Hacktoberfest: 

### ISSUE THREAD

**Issue by BaloneyBoy97** [oss-slu/lrda_website#153]
**Original Issue** https://github.com/oss-slu/lrda_website/issues/138

**Description**
**As** a user,
**I want** to access an "About" page,
**So that** I can learn more about the purpose and background of the application.

This should give a clear and concise description for your issue. You can expand on the specific details of what you want included on the "About" page if needed

**Tasks**
- [ ] Design the "About" page layout.
    - Ensure it is responsive and works on all screen sizes.
- [ ] Link the "About" page to the navigation bar or footer for easy access.
    - Ensure that the link is accessible from all pages.
- [ ] Ensure the "About" page follows the design system of the app (e.g., consistent fonts, colors, etc.).
- [ ] Test for accessibility (use of semantic HTML, alt text for images, etc.).
- [ ] regression free
    - committed code will not break other functionalities or previous commits
- [ ] Create a test cases for your code 
    - [ ] Ensure that the tour starts correctly.
    - [ ] Ensure that users can skip or continue the tour seamlessly.
    - [ ] Ensure that the tour progresses step-by-step without issues.

**Acceptance Criteria**
- [ ] The "About" page is fully responsive and works on all screen sizes.
- [ ] The "About" page is accessible from the navigation bar or footer on all pages.
- [ ] All links on the "About" page (internal and external) work correctly.
- [ ] Code is well commented and adheres to the project’s code style.
- [ ] All test cases pass before merging the changes.
- [ ] The implementation should not break any existing functionality or pages.

**Comment by Sreeeja9866** [comment]
I will work on this issue

**Comment by Gayatrinj** [comment]
Hi, I’d like to work on this issue. Could you please assign it to me?

**Comment by BaloneyBoy97** [comment]
appreciate your willingness to contribute but currently all tasks related to this issue us resolved
