### ISSUE TITLE
Create Archive Feature for User's Note in the Desktop Application

### ISSUE THREAD

**Issue by BaloneyBoy97** [oss-slu/lrda_website#161]
Original Issue #139

**Description**
**As** a user,
**I need** the ability to archieve a note, including the uploaded media file (video, audio, photo) and its associated annotation, 
**So that** I can manage my content by removing unnecessary or outdated uploads.

**Tasks**
- [x] Ensure the archive button triggers the proper function when clicked.
    - [x] Change the "delete" button to "archive" button
- [x] Implement the backend logic to handle the archive of the media file and its associated annotation.
    - [x] Ensure that the note is archived from the database and any associated storage. 
- [x] Create confirmation prompts to avoid accidental deletion. (also note delete is not working can only handle archieve atm)
- [x] Ensure the archive process updates the UI to reflect the removal of the note.
    - [x]  Refresh or remove the archived note from the view without requiring a page reload.
- [x] Verify that the archive is regression-free.

**Acceptance Criteria**
- [ ] Code is well-commented.
- [ ] Code should pass the test case before merging.
- [ ] Users can successfully delete a note from their view.
- [ ] Deleted notes do not reappear after a page refresh or re-login.
- [ ] Backend data is correctly updated to reflect the archive note.
- [ ] Confirmation prompts work as expected before archive.

This issue complete last item on the MVP of the project.
