### ISSUE TITLE
Update on Frontend Introjs Tour Popup

### ISSUE THREAD

**Issue by BaloneyBoy97** [oss-slu/lrda_website#168]
**Original Issue** https://github.com/oss-slu/lrda_website/issues/138

**Description**

**As** a new user,
**I want** my on-boarding tour to have good UI Design,
**So that** I can easily navigate and use the map functionalities and refer back to the tour through the help section if needed.

**Tasks**
Install Intro.js:
- [ ] Create a test case for your code
- [ ] Adjust the Skip Button on IntroJs Popup
       - make it smaller
       - move button a little to the left
       - inspect overall design of the popup window and make it more atheistic
**Acceptance Criteria**
- [ ] Create at least one test case for you code
- [ ] Code is well commented
- [ ] Only commit changes that you physically typed.
- [ ] Code should pass the test case before merge
