### ISSUE TITLE
Update on Frontend Introjs Tour Popup Part 2

### ISSUE THREAD

**Issue by BaloneyBoy97** [oss-slu/lrda_website#170]
**Original Issue** https://github.com/oss-slu/lrda_website/issues/138

**Description**

**As** a new user,
**I want** my on-boarding tour to have good UI Design,
**So that** I can easily navigate and use the map functionalities and refer back to the tour through the help section if needed.

**Tasks**
Install Intro.js:
- [x] Create a test case for your code
- [ ] Adjust the map search highlight on IntroJs Popup
       - make it smaller
       - move button a little to the left
       - inspect overall design of the popup window and make it more atheistic
- [ ] adjust popup tour so it only shows up for user one time
       - a skip button or do not show button will stop the tour from showing
       - if a user went through the tour once it will not show up again
**Acceptance Criteria**
- [ ] Create at least one test case for you code
- [ ] Code is well commented
- [ ] Only commit changes that you physically typed.
- [ ] Code should pass the test case before merge
