### ISSUE TITLE
Front end notes component media upload button modification part 1

### ISSUE THREAD

**Issue by BaloneyBoy97** [oss-slu/lrda_website#177]
**Original Issue** https://github.com/oss-slu/lrda_website/issues/177

**Description**

**As** a new user,
**I want** my note component(media upload button) to have uniform Design,
**So that** I can easily navigate and use the notes functionalities .

**Tasks**

- [x] Create a test case for your code
- [x] Adjust the media upload button(video) on tool bar
       - move it to note editor where image upload is
       - remove it from tool bar
- [x] adjust back end so it uploads media file after the button is moved

**Acceptance Criteria**
- [x] Create at least one test case for you code
- [x] Code is well commented
- [x] Only commit changes that you physically typed.
- [x] Code should pass the test case before merge
