### ISSUE TITLE
Front end notes component media upload button modification part 2

### ISSUE THREAD

**Issue by BaloneyBoy97** [oss-slu/lrda_website#178]
**Original Issue** https://github.com/oss-slu/lrda_website/issues/138

**Description**

**As** a new user,
**I want** my note component(media upload button) to have uniform Design,
**So that** I can easily navigate and use the notes functionalities .

**Tasks**

- [ ] Create a test case for your code
- [ ] Adjust the media upload button(audio) on tool bar
       - move it to note editor where image upload is
       - remove it from tool bar
- [ ] adjust back end so it uploads media file after the button is moved

**Acceptance Criteria**
- [ ] Create at least one test case for you code
- [ ] Code is well commented
- [ ] Only commit changes that you physically typed.
- [ ] Code should pass the test case before merge
