### ISSUE TITLE
Adding contributor information in the About Page

### ISSUE THREAD

**Issue by BaloneyBoy97** [oss-slu/lrda_website#181]
Original Issue https://github.com/oss-slu/lrda_website/issues/160

Description
As a developer,
I want to add contributor information to the About page of the website,
So that users can see and acknowledge the developers who contributed to the project.

**Tasks**

- [ ] Design a section on the About page to display contributor(yours) information.
- [ ] Ensure that the layout is clean and visually appealing.
- [ ] Add GitHub and LinkedIn links for contributors (if you have both).
- [ ] Include relevant roles or contributions for each developer (if available).

- [ ] Ensure all links are functional and direct to the correct profiles.
- [ ] Verify that the information is displayed correctly across different browsers.
- [ ] Confirm the section is visually consistent with the rest of the About page.

**Comment by that-ar-guy** [comment]
Hey there @BaloneyBoy97  can i take this up

**Comment by BaloneyBoy97** [comment]
sorry man that is for the capstone student
